## I had to severaly restrict the sizes of both the dataset (20%) and the numbers of layers.  Otherwise, even with 12 cores @ 2.93GHz and 24Gb memory, my models just ran for too long (hours, or never finishing).

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

%matplotlib inline

In [2]:
artworks = pd.read_csv('Artworks.csv')

In [3]:
artworks.columns

Index(['Title', 'Artist', 'ConstituentID', 'ArtistBio', 'Nationality',
       'BeginDate', 'EndDate', 'Gender', 'Date', 'Medium', 'Dimensions',
       'CreditLine', 'AccessionNumber', 'Classification', 'Department',
       'DateAcquired', 'Cataloged', 'ObjectID', 'URL', 'ThumbnailURL',
       'Circumference (cm)', 'Depth (cm)', 'Diameter (cm)', 'Height (cm)',
       'Length (cm)', 'Weight (kg)', 'Width (cm)', 'Seat Height (cm)',
       'Duration (sec.)'],
      dtype='object')

In [4]:
# Select Columns.
artworks = artworks[['Artist', 'Nationality', 'Gender', 'Date', 'Department',
                    'DateAcquired', 'URL', 'ThumbnailURL', 'Height (cm)', 'Width (cm)']]

# Convert URL's to booleans.
artworks['URL'] = artworks['URL'].notnull()
artworks['ThumbnailURL'] = artworks['ThumbnailURL'].notnull()

# Drop films and some other tricky rows.
artworks = artworks[artworks['Department']!='Film']
artworks = artworks[artworks['Department']!='Media and Performance Art']
artworks = artworks[artworks['Department']!='Fluxus Collection']

# Drop missing data.
artworks = artworks.dropna()

In [5]:
artworks.head()

Artist Nationality  Gender  Date             Department  \
0               Otto Wagner  (Austrian)  (Male)  1896  Architecture & Design   
1  Christian de Portzamparc    (French)  (Male)  1987  Architecture & Design   
2                Emil Hoppe  (Austrian)  (Male)  1903  Architecture & Design   
3           Bernard Tschumi          ()  (Male)  1980  Architecture & Design   
4                Emil Hoppe  (Austrian)  (Male)  1903  Architecture & Design   

  DateAcquired   URL  ThumbnailURL  Height (cm)  Width (cm)  
0   1996-04-09  True          True      48.6000    168.9000  
1   1995-01-17  True          True      40.6401     29.8451  
2   1997-01-15  True          True      34.3000     31.8000  
3   1995-01-17  True          True      50.8000     50.8000  
4   1997-01-15  True          True      38.4000     19.1000

In [6]:
artworks.dtypes

Artist           object
Nationality      object
Gender           object
Date             object
Department       object
DateAcquired     object
URL                bool
ThumbnailURL       bool
Height (cm)     float64
Width (cm)      float64
dtype: object

In [7]:
artworks['DateAcquired'] = pd.to_datetime(artworks.DateAcquired)
artworks['YearAcquired'] = artworks.DateAcquired.dt.year
artworks['YearAcquired'].dtype

dtype('int64')

## Take a 20% sample to make this less painful (actually compute reasonably)

In [8]:
artworks = artworks.copy().sample(frac=0.20)

In [9]:
# Remove multiple nationalities, genders, and artists.
artworks.loc[artworks['Gender'].str.contains('\) \('), 'Gender'] = '\(multiple_persons\)'
artworks.loc[artworks['Nationality'].str.contains('\) \('), 'Nationality'] = '\(multiple_nationalities\)'
artworks.loc[artworks['Artist'].str.contains(','), 'Artist'] = 'Multiple_Artists'

# Convert dates to start date, cutting down number of distinct examples.
artworks['Date'] = pd.Series(artworks.Date.str.extract(
    '([0-9]{4})', expand=False))[:-1]

# Final column drops and NA drop.
X = artworks.drop(['Department', 'DateAcquired', 'Artist', 'Nationality', 'Date'], 1)

# Create dummies separately.
artists = pd.get_dummies(artworks.Artist)
nationalities = pd.get_dummies(artworks.Nationality)
dates = pd.get_dummies(artworks.Date)

# Concat with other variables, but artists slows this wayyyyy down so we'll keep it out for now
X = pd.get_dummies(X, sparse=True)
X = pd.concat([X, nationalities, dates], axis=1)

Y = artworks.Department

In [10]:
# Alright! We've done our prep, let's build the model.
# Neural networks are hugely computationally intensive.
# This may take several minutes to run.

# Import the model.
from sklearn.neural_network import MLPClassifier

# Establish and fit the model, with a single, 100 perceptron layer;
# Thinkful originally used 1000, which hung my machine several times.
# This was the only way I could get it to work.  Miraculously, it
# performed better than 1000 perceptrons....
mlp = MLPClassifier(hidden_layer_sizes=(100,))
mlp.fit(X, Y)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [11]:
mlp.score(X, Y)

0.692812602559895

In [12]:
Y.value_counts()/len(Y)

Drawings & Prints        0.618876
Photography              0.231234
Architecture & Design    0.114117
Painting & Sculpture     0.035773
Name: Department, dtype: float64

In [13]:
from sklearn.model_selection import cross_val_score
cross_val_score(mlp, X, Y, cv=5)

array([0.71197563, 0.59971877, 0.72105016, 0.68089097, 0.62875235])

## Let's drop redundancies

In [14]:
pd.set_option('display.max_columns', 500)
X.head(3)

URL  ThumbnailURL  Height (cm)  Width (cm)  YearAcquired  Gender_()  \
72725  False         False       76.700       56.40          1974          0   
73997   True          True       99.300       72.70          1975          0   
1082    True          True        9.525        5.08          1997          0   

       Gender_(Female)  Gender_(Male)  Gender_(male)  \
72725                0              1              0   
73997                0              1              0   
1082                 0              1              0   

       Gender_\(multiple_persons\)  ()  (Albanian)  (American)  (Argentine)  \
72725                            0   0           0           0            0   
73997                            0   0           0           0            0   
1082                             0   0           0           0            0   

       (Australian)  (Austrian)  (Belgian)  (Bolivian)  (Bosnian)  \
72725             0           0          0           0          0   
73997             0           0          0           0          0   
1082              0           0          0           0          0   

       (Brazilian)  (British)  (Bulgarian)  (Burkinabe)  (Cambodian)  \
72725            0          0            0            0            0   
73997            0          0            0            0            0   
1082             0          0            0            0            0   

       (Cameroonian)  (Canadian Inuit)  (Canadian)  (Chilean)  (Chinese)  \
72725              0                 0           0          0          0   
73997              0                 0           0          0          0   
1082               0                 0           0          0          0   

       (Colombian)  (Congolese)  (Coptic)  (Costa Rican)  (Croatian)  (Cuban)  \
72725            0            0         0              0           0        0   
73997            0            0         0              0           0        0   
1082             0            0         0              0           0        0   

       (Czech)  (Danish)  (Dutch)  (Ecuadorian)  (Egyptian)  (Finnish)  \
72725        0         0        0             0           0          0   
73997        0         0        0             0           0          0   
1082         0         0        0             0           0          0   

       (French)  (Georgian)  (German)  (Greek)  (Guatemalan)  (Guyanese)  \
72725         0           0         0        0             0           0   
73997         1           0         0        0             0           0   
1082          0           0         0        0             0           0   

       (Haitian)  (Hungarian)  (Icelandic)  (Indian)  (Irish)  (Israeli)  \
72725          0            0            0         0        0          0   
73997          0            0            0         0        0          0   
1082           0            0            0         0        0          0   

       (Italian)  (Japanese)  (Kenyan)  (Korean)  (Kuwaiti)  (Latvian)  \
72725          1           0         0         0          0          0   
73997          0           0         0         0          0          0   
1082           1           0         0         0          0          0   

       (Lebanese)  (Lithuanian)  (Luxembourgish)  (Macedonian)  (Malian)  \
72725           0             0                0             0         0   
73997           0             0                0             0         0   
1082            0             0                0             0         0   

       (Mexican)  (Moroccan)  (Nationality Unknown)  (Nationality unknown)  \
72725          0           0                      0                      0   
73997          0           0                      0                      0   
1082           0           0                      0                      0   

       (Nigerian)  (Norwegian)  (Pakistani)  (Palestinian)  (Panamanian)  \
72725           0            0            0         

## Obviously, some of these features are redundant: Gender(Female), Gender(), & Gender_multiplepersons contain all of the variance for gender - 4 columns that say the same thing.
## In the same vein, we shouldn't keep YearAcquired – it's redundant with the dummy columns, and the MLP model won't be great at interpreting its scale as-is.

In [15]:
X2 = X.drop(['Gender_(Male)', 'Gender_(male)', 'YearAcquired'], axis=1)

In [16]:
# Test the altered data with the same MLP configuration used earlier in the assignment.
mlp2 = MLPClassifier(hidden_layer_sizes=(100,))
mlp2.fit(X2, Y)
mlp2.score(X2, Y)

0.8942285151671433

In [17]:
cross_val_score(mlp2, X2, Y, cv=5)

array([0.79798453, 0.8057183 , 0.80028129, 0.79835873, 0.8032364 ])

## Already some significant lift.  Let's play a bit more with hidden layers.

In [18]:
# Test the altered data with different MLP configuration
mlp2 = MLPClassifier(hidden_layer_sizes=(25,25,25,25,))
mlp2.fit(X2, Y)
mlp2.score(X2, Y)

0.8816634628908997

In [19]:
cross_val_score(mlp2, X2, Y, cv=5)

array([0.7862667 , 0.78556363, 0.78059072, 0.7943728 , 0.77673546])

## Slightly worse.  Obviously the best way would be a gridsearch.